package archivehunter

trait ArchiveHunterLookupResult

case class ArchiveHunterFound(archiveHunterId:String, archiveHunterCollection:String) extends ArchiveHunterLookupResult
case object ArchiveHunterNotFound extends ArchiveHunterLookupResult
